Throw specific exception when no data type specified for root group
hdmf-dev/hdmf pull request #157
Opened 2019-09-29 07:49 UTC by rly

This is helpful to address https://github.com/NeurodataWithoutBorders/pynwb/issues/1077 where an incompatible file is read.

2019-09-29 14:06 UTC, t-b commented
@rly How about detecting NWBv1 files as well and give the user a good error message. If written and found something at https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/nwb_reader.py#L606.

2019-09-29 17:38 UTC, rly commented
@t-b thanks for the code snippet. I had started to write something similar in pynwb which relies on catching the above exception, but maybe the NWB version should be checked before triggering the whole builder parsing logic. I'll put up a PR in pynwb soon for feedback.

2019-09-30 16:22 UTC, oruebel approved these changes

2019-09-30 16:53 UTC, ajtritt requested changes
I'm not sure what the best solution is, but this seems like it could be a bandage on a larger problem. `root` could not have a `data_type` if you just added some objects (with `data_type`) to the root group, which seems like a perfectly okay thing to do.

2019-09-30 16:53 UTC, ajtritt commented on src/hdmf/backends/hdf5/h5tools.py
> +class MissingRootException(ValueError):
I don't think this should ever happen. Root always exists by definition.

2019-10-08 17:06 UTC, rly commented
Rethinking this, I agree with @ajtritt that this is not the best approach to the problem.

2019-10-08 17:06 UTC, closed without merging