try using numpy to determine shape
hdmf-dev/hdmf pull request #229
Opened 2020-01-02 17:18 UTC by bendichter

## Motivation

`np.shape` determines the shape of an array by reading the data in place
without copying, so it should be more efficient than loading the data
and more robust to cases where no data load is enforced.

also, fix #228

2020-01-03 02:18 UTC, rly requested changes

2020-01-03 02:18 UTC, rly commented on src/hdmf/utils.py
> +        return
Style comment: I would prefer being explicit about the return value
```suggestion
        return None
```

2020-01-03 02:18 UTC, rly commented on src/hdmf/utils.py
> -        return None
Style comment: I would prefer to be explicit with return values for functions where a return value is expected, so I would add `return None` here.

2020-06-18 03:59 UTC, rly commented on src/hdmf/utils.py
>      if hasattr(data, 'maxshape'):
To maintain existing behavior where maxshape is checked before shape, this check should go before `np.shape`

2020-06-18 04:05 UTC, rly commented on src/hdmf/utils.py
> +    if hasattr(data, 'shape'):
This is redundant with `np.shape`. See https://github.com/numpy/numpy/blob/v1.18.4/numpy/core/fromnumeric.py#L1903-L1946

2020-06-18 06:32 UTC, rly commented on src/hdmf/utils.py
> +    if hasattr(data, 'shape'):
never mind

2020-06-18 06:45 UTC, rly commented on src/hdmf/utils.py
>          if not strict_no_data_load or (isinstance(data, list) or isinstance(data, tuple) or isinstance(data, set)):
Should this have been `strict_no_data_load and (isinstance...`?

2020-06-18 07:47 UTC, rly commented
@bendichter I made some changes to your PR, including adding needed tests for `get_data_shape`, but I could not come up with a use case / MWE where the use of `np.shape` is better than what we currently have. Could you give an example?

2020-06-24 22:22 UTC, bendichter commented
We decided to remove the changes to the shape check but keep the tests

2020-06-25 16:58 UTC, closed without merging