Pass parent properties to extended dataset/attribute
hdmf-dev/hdmf pull request #321
Opened 2020-03-25 02:08 UTC by rly

Fix #320 
`'dtype'`, `'shape'`, `'dims'` are passed to extended dataset if not specified
`'shape'` and `'dims'` are passed to extended attribute if not specified

I also added TODOs in the code for testing compatibility between the extended dataset/attribute's dtype/shape/dims with the parent's values. Should we test for those? If so, I will make a separate issue ticket and PR.

e.g., if the parent dataset has dtype `'int'`, the extending dataset should not be allowed to be defined with dtype `'text'`. However, if the parent dataset has dtype `'numeric'`, the extending dataset should be allowed to refined the dtype to be `'int'`. 

For shape, I think we should only allow pruning of options, not expansion of options. e.g., if the parent dataset has shape `[None]`, the extending dataset should be allowed to be defined with shape `[3]` but not `[[None], [None, None]]`.

2020-04-01 21:20 UTC, ajtritt commented on src/hdmf/spec/spec.py
> +                # TODO: test whether child dtype is compatible with parent dtype
add check to make sure child is a subset of parent

2020-04-01 21:22 UTC, ajtritt requested changes
Please fill in the TODOs

2020-04-01 21:22 UTC, ajtritt commented on src/hdmf/spec/spec.py
> +                # TODO: test whether child dtype is compatible with parent dtype
add check to make sure child is a subset of parent

2020-04-01 21:22 UTC, ajtritt commented on src/hdmf/spec/spec.py
> +                # TODO: test whether child shape is compatible with parent shape
add check to make sure child is a subset of parent

2020-04-01 21:22 UTC, ajtritt commented on src/hdmf/spec/spec.py
> +                        # TODO: test whether child shape is compatible with parent shape
add check to make sure child is a subset of parent

2020-04-01 21:22 UTC, ajtritt commented on src/hdmf/spec/spec.py
> +                        # TODO: test whether child dims is compatible with parent dims
add check to make sure child is a subset of parent

2025-10-03 21:52 UTC, rly commented
Replaced by #1312.

2025-10-03 21:52 UTC, closed without merging