Get multi container interface
hdmf-dev/hdmf pull request #420
Opened 2020-08-21 13:35 UTC by bendichter

## Motivation

Use `get_class` to automatically generate a `MultiContainerInterface`.

address https://github.com/NeurodataWithoutBorders/pynwb/issues/888
## How to test the behavior?
```python
multi_spec = GroupSpec('A test extension that contains a multi',
                               data_type_def='Multi',
                               groups=[GroupSpec(
                                   data_type_inc=self.bar_spec,
                                   doc='test multi',
                                   quantity='*')]
                               )
        self.spec_catalog.register_spec(multi_spec, 'extension.yaml')
        Bar = self.type_map.get_container_cls(CORE_NAMESPACE, 'Bar')
        Multi = self.type_map.get_container_cls(CORE_NAMESPACE, 'Multi')
        assert Multi.__clsconf__[0] == dict(
            attr='bars',
            type=Bar,
            add='add_bars',
            get='get_bars',
            create='create_bars'
        )

        multi = Multi(bars=[Bar('my_bar', list(range(10)), 'value1', 10)])
        assert multi.bars['my_bar'] == Bar('my_bar', list(range(10)), 'value1', 10)
```

## Checklist

- [ ] Did you update CHANGELOG.md with your changes?
- [ ] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR clearly describes the problem and the solution?
- [ ] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [ ] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

2020-08-21 13:36 UTC, bendichter commented on src/hdmf/build/manager.py
> +        """Build docval for new class
```suggestion
        """Build docval for auto-generated class
```

2020-08-21 17:28 UTC, oruebel commented
@bendichter thanks for the PR! @rly @ajtritt  can you review, I don't know the class generation code well enough to review.

2020-08-22 01:06 UTC, rly commented on src/hdmf/build/manager.py
> +            if getattr(field_spec, 'quantity', None) in ('*', '?'):
```suggestion
            if getattr(field_spec, 'quantity', None) in (ZERO_OR_MANY, ONE_OR_MANY):
```

2020-08-22 01:06 UTC, rly commented on src/hdmf/build/manager.py
>  from ..spec import AttributeSpec, DatasetSpec, GroupSpec, LinkSpec, NamespaceCatalog, RefSpec, SpecReader
```suggestion
from ..spec import (AttributeSpec, DatasetSpec, GroupSpec, LinkSpec, NamespaceCatalog, RefSpec, SpecReader,
                   ZERO_OR_MANY, ONE_OR_MANY)
```

2020-08-22 01:07 UTC, rly commented on src/hdmf/build/manager.py
> +            if getattr(field_spec, 'quantity', None) in ('*', '?'):
```suggestion
            if getattr(field_spec, 'quantity', None) in (ZERO_OR_MANY, ONE_OR_MANY):
```

2020-08-22 01:10 UTC, rly commented on src/hdmf/build/manager.py
> +                docval_arg.update(type=(list, tuple))
```suggestion
                docval_arg.update(type=(list, tuple, dict, self.__get_type(field_spec)))
```

2020-08-22 01:13 UTC, rly commented on src/hdmf/build/manager.py
> +        if len(clsconf):
To organize the code, I would move these two lines to line 596

2020-08-23 15:56 UTC, bendichter commented
@rly good suggestions. I made the changes you requested.

2020-08-25 20:59 UTC, rly commented on src/hdmf/build/manager.py
> +    def build_docval(self, base, addl_fields, name=None, default_name=None):
```suggestion
    def __build_docval(self, base, addl_fields, name=None, default_name=None):
```

2020-08-25 20:59 UTC, rly commented on src/hdmf/build/manager.py
> +        docval_args = self.build_docval(base, addl_fields, name, default_name)
```suggestion
        docval_args = self.__build_docval(base, addl_fields, name, default_name)
```

2020-08-25 21:00 UTC, rly commented on src/hdmf/build/manager.py
> +    def build_docval(self, base, addl_fields, name=None, default_name=None):
If this is not meant to be called by other classes, make it "private". Otherwise, please add unit tests for this method

2020-08-25 21:15 UTC, rly commented on src/hdmf/build/manager.py
> +                    raise ValueError("Got \"None\" for field specification: {}".format(field_spec))
```suggestion
```
This code is unreachable and can be safely removed.

2020-08-25 21:26 UTC, bendichter commented
@rly how do you feel about compromising with a single underscore instead of double underscore?

2020-08-25 21:28 UTC, ajtritt commented
@bendichter @rly 

`build_docval` -> `_build_docval`  + unit test

2020-08-25 21:30 UTC, bendichter commented
@ajtritt ok

2020-08-25 21:46 UTC, rly commented
I added some tests to try to achieve 100% diff coverage.

2020-08-25 21:53 UTC, bendichter commented
@rly those look good, but I think @ajtritt is right that we should have unit tests for each function. I am working on a simple test for build_docval specifically that we can also add. I'm running into a weird syntax thing but should be done soon.

2020-08-25 21:58 UTC, ajtritt requested changes

2020-08-25 21:58 UTC, ajtritt commented on tests/unit/build_tests/test_io_map.py
> +        Multi = self.type_map.get_container_cls(CORE_NAMESPACE, 'Multi')
```suggestion
        Multi = self.type_map.get_container_cls(CORE_NAMESPACE, 'Multi')
        assert issubclass(Multi, MultiContainerInterface)
```

2020-08-25 23:58 UTC, rly commented on src/hdmf/build/manager.py
> +                    x['default'] = default_name
I added a test for this and broke a ton of other unrelated tests. It turns out that line 514 does not copy the dicts within the docval tuple, but copies references to the dicts, so the line above changes the 'name' docval arg for the base class. I'll fix this

2020-08-26 00:30 UTC, rly commented on src/hdmf/build/manager.py
> +                        setattr(self, f, arg_val)
```suggestion
                    setattr(self, f, arg_val)
```
I'm pretty sure this branch is not necessary. The setter for `AbstractContainer` already checks for None and will not set it if so

2020-08-26 00:34 UTC, rly submitted a review, later dismissed

2020-08-26 01:13 UTC, rly approved these changes

2020-08-26 01:22 UTC, bendichter commented
@ajtritt I think this is ready to go. When you get a chance can you review?

2020-08-26 02:04 UTC, ajtritt approved these changes

2020-08-26 12:03 UTC, merged