add multi_index code and test
hdmf-dev/hdmf pull request #430
Opened 2020-10-01 16:10 UTC by bendichter

## Motivation

fix https://github.com/NeurodataWithoutBorders/pynwb/issues/1296

Having some issues with read though

@rly, could you take a look at this?

## Checklist

- [ ] Did you update CHANGELOG.md with your changes?
- [ ] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR clearly describes the problem and the solution?
- [ ] Is your contribution compliant with our coding style? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf/pulls) for the same change?
- [ ] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

2020-10-12 17:13 UTC, bendichter commented
to do: 

* add description to docval
* add test: use __columns__

2020-10-12 17:13 UTC, rly commented on src/hdmf/common/table.py
> +            {'name': 'index', 'type': (bool, VectorIndex, 'array_data', int),
Document 'int' dtype (and others)

2020-10-12 17:14 UTC, rly commented on tests/unit/common/test_table.py
> +    def test_add_column_multi_index(self):
Add test with `DynamicTable` subclass with `__columns__` where index=int

2020-10-12 17:22 UTC, ajtritt requested changes
Add more documentation to add_column. Eventually lets refactor this function to make it easier to maintain.

2020-10-13 16:17 UTC, rly approved these changes
Looks good to me

2020-10-13 16:23 UTC, ajtritt approved these changes

2020-10-13 16:33 UTC, merged