Fix #81 - store all lists of strings as unicode instead of ascii
hdmf-dev/hdmf pull request #82
Opened 2019-06-08 22:29 UTC by rly

2019-06-11 18:38 UTC, ajtritt requested changes

2019-06-11 18:38 UTC, ajtritt commented on src/hdmf/backends/hdf5/h5tools.py
> +                        value = [np.unicode_(s) for s in tmp]
Just delete this, so the values get written in the format that they are passed in as.

2019-06-14 19:01 UTC, rly commented
@ajtritt this should be good to go now

2019-06-19 21:29 UTC, ajtritt approved these changes

2019-06-20 22:58 UTC, merged